# Generated by Django 6.1.1 on 2026-09-04 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('careers_url', models.URLField(blank=True, help_text='Where this company lists its openings.', verbose_name='careers page')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('industry', models.CharField(blank=True, max_length=120, verbose_name='industry')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'company',
                'verbose_name_plural': 'companies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='role')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='jobs.company', verbose_name='company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'contact',
                'verbose_name_plural': 'contacts',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('remote_type', models.CharField(blank=True, choices=[('onsite', 'On site'), ('hybrid', 'Hybrid'), ('remote', 'Remote')], max_length=20, verbose_name='working arrangement')),
                ('employment_type', models.CharField(blank=True, choices=[('full_time', 'Full time'), ('part_time', 'Part time'), ('contract', 'Contract'), ('freelance', 'Freelance'), ('internship', 'Internship'), ('apprenticeship', 'Apprenticeship')], max_length=20, verbose_name='employment type')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='posting URL')),
                ('source', models.CharField(blank=True, help_text='Where you came across it: a job board, a referral, the company site.', max_length=120, verbose_name='found via')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('salary_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='salary from')),
                ('salary_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='salary to')),
                ('salary_currency', models.CharField(blank=True, default='EUR', max_length=3, verbose_name='currency')),
                ('salary_period', models.CharField(blank=True, choices=[('year', 'Per year'), ('month', 'Per month'), ('day', 'Per day'), ('hour', 'Per hour')], default='year', max_length=10, verbose_name='salary period')),
                ('posted_at', models.DateField(blank=True, null=True, verbose_name='posted on')),
                ('closes_at', models.DateField(blank=True, help_text='The application deadline, if stated.', null=True, verbose_name='closing date')),
                ('closed_at', models.DateTimeField(blank=True, help_text='Set when the opening is no longer available.', null=True, verbose_name='closed on')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postings', to='jobs.company', verbose_name='company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'job posting',
                'verbose_name_plural': 'job postings',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_company_name_per_owner'),
        ),
    ]
