# Generated by Django 6.1.1 on 2026-09-04 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_sent_uploads'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Capture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='address')),
                ('source_name', models.CharField(blank=True, max_length=60, verbose_name='read by')),
                ('source_version', models.CharField(blank=True, max_length=20, verbose_name='source version')),
                ('origin', models.CharField(default='web', help_text='Which part of Postulo produced this: the web interface, or the API.', max_length=20, verbose_name='captured from')),
                ('data', models.JSONField(default=dict, verbose_name='parsed posting')),
                ('status', models.CharField(choices=[('pending', 'Waiting for review'), ('accepted', 'Turned into an application'), ('discarded', 'Discarded')], default='pending', max_length=20, verbose_name='status')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='applications.application', verbose_name='application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'capture',
                'verbose_name_plural': 'captures',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['owner', 'status'], name='jobs_captur_owner_i_8fee5c_idx')],
            },
        ),
    ]
