# Generated by Django 6.1.1 on 2026-09-05 15:12, then given the data step below.

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def date_existing_postings(apps, schema_editor):
    """Postings from before listings existed entered — and were decided — when created.

    Every one of them has an application (nothing else could create a posting), so their
    derived state is *applied* whatever the stored state says. Only the dates need filling.
    """
    JobPosting = apps.get_model("jobs", "JobPosting")
    for posting in JobPosting.objects.all().iterator():
        posting.noted_at = posting.created_at
        posting.decided_at = posting.created_at
        posting.save(update_fields=["noted_at", "decided_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_capture'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobposting',
            options={'ordering': ('-noted_at', '-created_at'), 'verbose_name': 'job posting', 'verbose_name_plural': 'job postings'},
        ),
        migrations.AddField(
            model_name='capture',
            name='posting',
            field=models.ForeignKey(blank=True, help_text='The listing this capture became, once reviewed.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='captures', to='jobs.jobposting', verbose_name='listing'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='decided_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='decided on'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='discard_reason',
            field=models.CharField(blank=True, choices=[('not_for_me', 'Not for me'), ('pay', 'The pay'), ('location', 'The location'), ('closed', 'Closed or already filled'), ('other', 'Other')], max_length=20, verbose_name='why it was discarded'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='noted_at',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='When it entered your listings.', verbose_name='noted on'),
        ),
        migrations.AddField(
            model_name='jobposting',
            name='state',
            field=models.CharField(choices=[('new', 'New'), ('shortlisted', 'Shortlisted'), ('discarded', 'Discarded')], default='new', max_length=20, verbose_name='state'),
        ),
        migrations.AddIndex(
            model_name='jobposting',
            index=models.Index(fields=['owner', 'state'], name='jobs_jobpos_owner_i_a7eca7_idx'),
        ),
        migrations.RunPython(date_existing_postings, migrations.RunPython.noop),
    ]
