# Generated by Django 6.1.1 on 2026-09-05 17:55

import django.db.models.deletion
from django.conf import settings
import re

from django.db import migrations, models
from django.utils.text import slugify


def _split(text):
    return [part.strip() for part in re.split(r"[;,/]", text or "") if part.strip()]


def industries_from_strings(apps, schema_editor):
    """Every industry string becomes rows in its owner's vocabulary, linked to the company.

    "Software, Insurance" typed into the one box becomes two industries; nothing is
    lost and nothing needs retyping.
    """
    Company = apps.get_model("jobs", "Company")
    Industry = apps.get_model("jobs", "Industry")
    for company in Company.objects.exclude(industry="").iterator():
        for name in _split(company.industry):
            slug = slugify(name)[:60] or "other"
            industry, _created = Industry.objects.get_or_create(
                owner_id=company.owner_id, slug=slug, defaults={"name": name[:60]}
            )
            company.industries.add(industry)


def strings_from_industries(apps, schema_editor):
    Company = apps.get_model("jobs", "Company")
    for company in Company.objects.prefetch_related("industries").iterator():
        names = [industry.name for industry in company.industries.all()]
        if names:
            company.industry = ", ".join(names)[:120]
            company.save(update_fields=["industry"])


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_listings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, verbose_name='slug')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'industry',
                'verbose_name_plural': 'industries',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='company',
            name='industries',
            field=models.ManyToManyField(blank=True, related_name='companies', to='jobs.industry', verbose_name='industries'),
        ),
        migrations.AddConstraint(
            model_name='industry',
            constraint=models.UniqueConstraint(fields=('owner', 'slug'), name='unique_industry_slug_per_owner'),
        ),
        migrations.RunPython(industries_from_strings, strings_from_industries),
        migrations.RemoveField(model_name="company", name="industry"),
    ]
