# Generated by Django 6.1.1 on 2026-09-05 22:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0004_industries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('scheme', models.CharField(choices=[('wikidata', 'Wikidata'), ('lei', 'Legal Entity Identifier (LEI)'), ('register', 'Company register number'), ('linkedin', 'LinkedIn'), ('crunchbase', 'Crunchbase'), ('opencorporates', 'OpenCorporates'), ('other', 'Other')], max_length=20, verbose_name='scheme')),
                ('value', models.CharField(max_length=100, verbose_name='identifier')),
                ('label', models.CharField(blank=True, help_text='What the identifier is, when the scheme is Other.', max_length=60, verbose_name='name')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='jobs.company', verbose_name='company')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'company identifier',
                'verbose_name_plural': 'company identifiers',
                'ordering': ('scheme', 'value'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('scheme', 'other'), _negated=True), fields=('company', 'scheme'), name='one_identifier_per_scheme_per_company'), models.UniqueConstraint(condition=models.Q(('scheme', 'other'), _negated=True), fields=('owner', 'scheme', 'value'), name='one_company_per_identifier_per_owner'), models.UniqueConstraint(fields=('company', 'scheme', 'label', 'value'), name='unique_other_identifier_per_company')],
            },
        ),
    ]
