# Generated by Django 6.1.1 on 2026-09-06 14:42

import postulo.jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_company_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.FileField(blank=True, max_length=255, upload_to=postulo.jobs.models.logo_upload_to, verbose_name='logo'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_fetched_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='logo fetched'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_source',
            field=models.CharField(blank=True, choices=[('url', 'From an address'), ('website', 'Found on their website'), ('upload', 'Uploaded')], max_length=10, verbose_name='where the logo came from'),
        ),
        migrations.AddField(
            model_name='company',
            name='logo_source_url',
            field=models.CharField(blank=True, max_length=500, verbose_name='logo address'),
        ),
    ]
