# Generated by Django 6.1.1 on 2026-09-09 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_remove_contact_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The company this one belongs to, if it belongs to one.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='jobs.company', verbose_name='part of'),
        ),
    ]
