# Generated by Django 6.1.1 on 2026-09-12 19:31

from django.db import migrations


"""The columns go once their values are rows (#189). Depends on the carry-across so that
rolling back puts the primaries back into them.
"""

class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_carry_web_links_across"),
        ('jobs', '0011_industry_nace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='linkedin_url',
        ),
    ]
