# Generated by Django 6.1.1 on 2026-09-15 13:05

"""A kind on every company, employer by default: the migration invents nothing, and the
employment service a person is registered with can be recorded as what it is (#202).
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_remove_contact_linkedin_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='kind',
            field=models.CharField(choices=[('employer', 'Employer'), ('employment_service', 'Employment service')], default='employer', max_length=20, verbose_name='kind'),
        ),
    ]
