# Generated by Django 6.1.1 on 2026-09-24 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_closing_soon_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='isco_code',
            field=models.CharField(blank=True, editable=False, max_length=4, verbose_name='ISCO-08 code'),
        ),
    ]
