# Generated by Django 6.1.1 on 2026-09-24 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0017_jobposting_isco_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='location_lat',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='latitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='location_lon',
            field=models.FloatField(blank=True, editable=False, null=True, verbose_name='longitude'),
        ),
        migrations.AddField(
            model_name='company',
            name='location_resolved_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='location resolved'),
        ),
        migrations.AddField(
            model_name='company',
            name='location_resolved_by',
            field=models.CharField(blank=True, choices=[('geonames', 'Matched from the city dataset'), ('manual', 'Set by the person recording it'), ('unplaced', 'Deliberately not placed')], max_length=20, verbose_name='location resolved by'),
        ),
        migrations.AddField(
            model_name='company',
            name='location_resolved_from',
            field=models.CharField(blank=True, max_length=200, verbose_name='location resolved from'),
        ),
    ]
