# Generated by Django 6.1.1 on 2026-09-28 22:20

import django.db.models.deletion
import postulo.jobs.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_company_location_coordinates'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapturedPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source', models.FileField(blank=True, max_length=255, upload_to=postulo.jobs.models.page_upload_to, verbose_name='source')),
                ('source_size', models.PositiveIntegerField(default=0, verbose_name='size of the source')),
                ('source_stored', models.PositiveIntegerField(default=0, verbose_name='size of the source on disk')),
                ('source_checksum', models.CharField(blank=True, max_length=64, verbose_name='checksum of the source')),
                ('rendering', models.FileField(blank=True, max_length=255, upload_to=postulo.jobs.models.page_upload_to, verbose_name='rendering')),
                ('rendering_type', models.CharField(blank=True, choices=[('image/png', 'PNG image'), ('image/jpeg', 'JPEG image'), ('image/webp', 'WebP image'), ('application/pdf', 'PDF')], max_length=20, verbose_name='kind of rendering')),
                ('rendering_size', models.PositiveIntegerField(default=0, verbose_name='size of the rendering')),
                ('rendering_checksum', models.CharField(blank=True, max_length=64, verbose_name='checksum of the rendering')),
                ('rendered_by', models.CharField(blank=True, choices=[('client', 'Sent with the capture, by the browser that was looking at the page'), ('instance', 'Drawn by this instance from the kept source')], max_length=10, verbose_name='drawn by')),
                ('capture', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='page', to='jobs.capture', verbose_name='capture')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'captured page',
                'verbose_name_plural': 'captured pages',
                'ordering': ('-created_at', '-pk'),
            },
        ),
    ]
