# Generated by Django 6.1.1 on 2026-09-29 12:40

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0019_captured_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('note', 'Note'), ('email_received', 'Email received'), ('call', 'Call'), ('message', 'Message'), ('document', 'Document'), ('capture', 'Capture'), ('other', 'Other')], default='note', max_length=20, verbose_name='kind')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='happened on')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='summary')),
                ('body', models.TextField(blank=True, verbose_name='details')),
                ('artefact_id', models.PositiveBigIntegerField(blank=True, null=True)),
                ('external_id', models.CharField(blank=True, max_length=250, verbose_name='identifier at the source')),
                ('actor', models.CharField(blank=True, max_length=120, verbose_name='recorded by')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded on')),
                ('artefact_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='kind of thing it points at')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listing_events', to='jobs.contact', verbose_name='from')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='jobs.jobposting', verbose_name='listing')),
            ],
            options={
                'verbose_name': 'listing entry',
                'verbose_name_plural': 'listing entries',
                'ordering': ('-occurred_at', '-pk'),
                'indexes': [models.Index(fields=['posting', '-occurred_at'], name='listing_event_latest'), models.Index(fields=['artefact_type', 'artefact_id'], name='listing_event_artefact')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('posting', 'external_id'), name='listing_event_once_per_source_id')],
            },
        ),
    ]
