# Generated by Django 6.1.1 on 2026-09-29 16:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_listing_history'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='capture',
            name='learning',
            field=models.JSONField(blank=True, default=dict, editable=False, verbose_name='what the review learns from'),
        ),
        migrations.CreateModel(
            name='FieldHint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('host', models.CharField(max_length=253, verbose_name='site')),
                ('field', models.CharField(choices=[('title', 'Job title'), ('company_name', 'Company'), ('location', 'Location'), ('employment_type', 'Employment type'), ('salary', 'Salary'), ('closes_at', 'Closing date'), ('description', 'Description')], max_length=20, verbose_name='field')),
                ('place', models.JSONField(default=dict, verbose_name='place on the page')),
                ('misses', models.PositiveSmallIntegerField(default=0, verbose_name='wrong in a row')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'remembered place',
                'verbose_name_plural': 'remembered places',
                'ordering': ('host', 'field'),
                'constraints': [models.UniqueConstraint(fields=('owner', 'host', 'field'), name='one_place_per_field_per_site')],
            },
        ),
    ]
