# Generated by Django 6.1.1 on 2026-10-03 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('jobs', '0021_remembered_places'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='capturedpage',
            name='rendering_type',
            field=models.CharField(blank=True, choices=[('image/png', 'PNG image'), ('image/jpeg', 'JPEG image'), ('image/webp', 'WebP image'), ('application/pdf', 'PDF')], max_length=20, verbose_name='type of rendering'),
        ),
        migrations.AlterField(
            model_name='company',
            name='kind',
            field=models.CharField(choices=[('employer', 'Employer'), ('employment_service', 'Employment service')], default='employer', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='listingevent',
            name='artefact_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='type of thing it points at'),
        ),
        migrations.AlterField(
            model_name='listingevent',
            name='kind',
            field=models.CharField(choices=[('note', 'Note'), ('email_received', 'Email received'), ('call', 'Call'), ('message', 'Message'), ('document', 'Document'), ('capture', 'Capture'), ('other', 'Other')], default='note', max_length=20, verbose_name='type'),
        ),
        migrations.AlterConstraint(
            model_name='companyidentifier',
            name='one_identifier_per_scheme_per_company',
            constraint=models.UniqueConstraint(condition=models.Q(('scheme', 'other'), _negated=True), fields=('company', 'scheme'), name='one_identifier_per_scheme_per_company', violation_error_message='This type of identifier is already listed.'),
        ),
    ]
