# Generated by Django 6.1.1 on 2026-10-03 21:48

from django.db import migrations, models

from postulo.core import slugs


def merge_and_rederive(apps, schema_editor):
    """Industries left with one name become one, their companies moved to the oldest; every
    slug that is not the one its name gives is derived again (#356)."""
    Industry = apps.get_model("jobs", "Industry")
    Through = apps.get_model("jobs", "Company").industries.through
    kept = {}
    for industry in Industry.objects.order_by("pk"):
        key = (industry.owner_id, slugs.fold(industry.name))
        keeper = kept.setdefault(key, industry)
        if keeper.pk == industry.pk:
            continue
        have = set(Through.objects.filter(industry_id=keeper.pk).values_list("company_id", flat=True))
        for company_id in Through.objects.filter(industry_id=industry.pk).values_list(
            "company_id", flat=True
        ):
            if company_id not in have:
                Through.objects.create(company_id=company_id, industry_id=keeper.pk)
        industry.delete()
    slugs.rederive(Industry, fallback="industry")


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_type_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='industry',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=160, verbose_name='slug'),
        ),
        migrations.RunPython(merge_and_rederive, migrations.RunPython.noop),
    ]
