# Generated by Django 6.1.1 on 2026-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_name_keys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='kind',
            field=models.CharField(choices=[('employer', 'Employer'), ('employment_service', 'Public employment service')], default='employer', max_length=20, verbose_name='type'),
        ),
    ]
