# Generated by Django 6.1.1 on 2026-10-05 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_public_employment_service_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposting',
            name='description_format',
            field=models.CharField(choices=[('plain', 'Plain text'), ('markdown', 'Markdown')], default='plain', max_length=10, verbose_name='description format'),
        ),
    ]
