# Generated by Django 6.1.1 on 2026-10-06 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_description_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='from_career',
            field=models.BooleanField(default=False, help_text='Added from an entry in your career. It is left out of the lists where you pick a company for new work, until you attach a listing, a person or an application to it.', verbose_name='from your career'),
        ),
    ]
