# Generated by Django 6.1.1 on 2026-10-06 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_company_from_career'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='has_logo',
            field=models.BooleanField(default=False, editable=False, verbose_name='has a logo'),
        ),
        migrations.CreateModel(
            name='CompanyLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField(verbose_name='picture')),
                ('media_type', models.CharField(editable=False, max_length=40, verbose_name='media type')),
                ('stored_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='stored at')),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stored_logo', to='jobs.company')),
            ],
            options={
                'verbose_name': 'company logo',
                'verbose_name_plural': 'company logos',
            },
        ),
    ]
