# Generated by Django 6.1.1 on 2026-10-06 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_move_logos_into_the_database'),
    ]

    operations = [
        migrations.AlterField(
            model_name='capture',
            name='posting',
            field=models.ForeignKey(blank=True, help_text='The listing this capture became, once reviewed.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='captures', to='jobs.jobposting', verbose_name='listing'),
        ),
    ]
