# Generated by Django 6.1.1 on 2026-09-04 17:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('applied', 'Applied'), ('acknowledged', 'Acknowledged'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted')], db_index=True, default='draft', max_length=20, verbose_name='status')),
                ('channel', models.CharField(blank=True, choices=[('company_site', 'Company website'), ('job_board', 'Job board'), ('email', 'Email'), ('referral', 'Referral'), ('recruiter', 'Recruiter'), ('event', 'Event or fair'), ('other', 'Other')], max_length=20, verbose_name='applied through')),
                ('priority', models.IntegerField(choices=[(1, 'Low'), (2, 'Normal'), (3, 'High')], default=2, verbose_name='priority')),
                ('applied_at', models.DateTimeField(blank=True, help_text='Set automatically the first time the status becomes “Applied”.', null=True, verbose_name='applied on')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='deadline')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='closed on')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.contact', verbose_name='main contact')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('posting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='jobs.jobposting', verbose_name='posting')),
                ('tags', models.ManyToManyField(blank=True, related_name='applications', to='core.tag', verbose_name='tags')),
            ],
            options={
                'verbose_name': 'application',
                'verbose_name_plural': 'applications',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ApplicationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('status_change', 'Status change'), ('note', 'Note'), ('email_sent', 'Email sent'), ('email_received', 'Email received'), ('call', 'Call'), ('interview', 'Interview'), ('assessment', 'Assessment or test'), ('offer', 'Offer received'), ('rejection', 'Rejection received'), ('follow_up', 'Followed up'), ('other', 'Other')], default='note', max_length=20, verbose_name='kind')),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='happened on')),
                ('summary', models.CharField(blank=True, max_length=250, verbose_name='summary')),
                ('body', models.TextField(blank=True, verbose_name='details')),
                ('from_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('applied', 'Applied'), ('acknowledged', 'Acknowledged'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted')], max_length=20, verbose_name='from status')),
                ('to_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('applied', 'Applied'), ('acknowledged', 'Acknowledged'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted')], max_length=20, verbose_name='to status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recorded on')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='applications.application', verbose_name='application')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ('-occurred_at', '-pk'),
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('summary', models.CharField(max_length=250, verbose_name='what to do')),
                ('due_at', models.DateTimeField(db_index=True, verbose_name='when')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='done on')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='applications.application', verbose_name='application')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'reminder',
                'verbose_name_plural': 'reminders',
                'ordering': ('due_at',),
            },
        ),
        migrations.AddIndex(
            model_name='application',
            index=models.Index(fields=['owner', 'status'], name='application_owner_i_85b28d_idx'),
        ),
    ]
