# Generated by Django 6.1.1 on 2026-09-04 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sent_uploads',
            field=models.ManyToManyField(blank=True, help_text='Files you already had, as opposed to documents Postulo rendered.', related_name='applications', to='documents.uploadeddocument', verbose_name='files sent'),
        ),
    ]
