# Generated by Django 6.1.1 on 2026-09-05 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_application_sent_uploads'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='notified_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='notified on'),
        ),
    ]
