# Generated by Django 6.1.1 on 2026-09-05 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_reminder_notified_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationevent',
            name='actor',
            field=models.CharField(blank=True, max_length=120, verbose_name='recorded by'),
        ),
    ]
