# Generated by Django 6.1.1 on 2026-09-05 17:29

import django.db.models.deletion
import postulo.applications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_event_actor'),
        ('jobs', '0003_listings'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationevent',
            name='kind',
            field=models.CharField(choices=[('status_change', 'Status change'), ('note', 'Note'), ('email_sent', 'Email sent'), ('email_received', 'Email received'), ('call', 'Call'), ('interview', 'Interview'), ('interview_scheduled', 'Interview scheduled'), ('interview_cancelled', 'Interview cancelled'), ('assessment', 'Assessment or test'), ('offer', 'Offer received'), ('rejection', 'Rejection received'), ('follow_up', 'Followed up'), ('other', 'Other')], default='note', max_length=20, verbose_name='kind'),
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('phone', 'Phone screen'), ('video', 'Video call'), ('onsite', 'On site'), ('panel', 'Panel'), ('assessment', 'Assessment or test'), ('other', 'Other')], default='video', max_length=20, verbose_name='kind')),
                ('starts_at', models.DateTimeField(db_index=True, verbose_name='starts')),
                ('ends_at', models.DateTimeField(verbose_name='ends')),
                ('location', models.CharField(blank=True, help_text='An address, or the link to the call.', max_length=500, verbose_name='where')),
                ('notes', models.TextField(blank=True, verbose_name='preparation notes')),
                ('outcome', models.CharField(choices=[('scheduled', 'Scheduled'), ('done', 'Held'), ('cancelled', 'Cancelled'), ('no_show', 'They did not show up')], db_index=True, default='scheduled', max_length=20, verbose_name='outcome')),
                ('uid', models.CharField(default=postulo.applications.models._mint_uid, max_length=64, verbose_name='calendar identifier')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.application', verbose_name='application')),
                ('contacts', models.ManyToManyField(blank=True, related_name='interviews', to='jobs.contact', verbose_name='who you are meeting')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('reminder', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interview', to='applications.reminder', verbose_name='reminder')),
            ],
            options={
                'verbose_name': 'interview',
                'verbose_name_plural': 'interviews',
                'ordering': ('starts_at', 'pk'),
                'constraints': [models.UniqueConstraint(fields=('owner', 'uid'), name='interview_uid_per_owner')],
            },
        ),
    ]
