# Generated by Django 6.1.1 on 2026-09-05 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_interviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='quiet_announced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='quiet announced on'),
        ),
    ]
