# Generated by Django 6.1.1 on 2026-09-06 13:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_application_quiet_announced'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('source', models.CharField(max_length=60, verbose_name='suggested by')),
                ('external_id', models.CharField(blank=True, max_length=250, verbose_name='identifier at the source')),
                ('kind', models.CharField(choices=[('status_change', 'Status change'), ('note', 'Note'), ('email_sent', 'Email sent'), ('email_received', 'Email received'), ('call', 'Call'), ('interview', 'Interview'), ('interview_scheduled', 'Interview scheduled'), ('interview_cancelled', 'Interview cancelled'), ('assessment', 'Assessment or test'), ('offer', 'Offer received'), ('rejection', 'Rejection received'), ('follow_up', 'Followed up'), ('other', 'Other')], default='note', max_length=20, verbose_name='kind')),
                ('summary', models.CharField(max_length=250, verbose_name='what it says')),
                ('body', models.TextField(blank=True, verbose_name='detail')),
                ('occurred_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='happened')),
                ('suggested_status', models.CharField(blank=True, choices=[('draft', 'Draft'), ('applied', 'Applied'), ('acknowledged', 'Acknowledged'), ('screening', 'Screening'), ('interviewing', 'Interviewing'), ('assessment', 'Assessment'), ('offer', 'Offer'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ghosted', 'Ghosted')], help_text='When accepting should also move the application.', max_length=20, verbose_name='suggested status')),
                ('proposed_dates', models.JSONField(blank=True, default=list, verbose_name='dates offered')),
                ('context', models.JSONField(blank=True, default=dict, verbose_name='context')),
                ('status', models.CharField(choices=[('pending', 'Waiting for review'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=20, verbose_name='status')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='reviewed on')),
                ('application', models.ForeignKey(blank=True, help_text='Empty when the source could not tell which application it is about.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='applications.application', verbose_name='application')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_suggestions', to='applications.applicationevent', verbose_name='timeline entry')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'suggestion',
                'verbose_name_plural': 'suggestions',
                'ordering': ('-occurred_at', '-pk'),
                'indexes': [models.Index(fields=['owner', 'status'], name='application_owner_i_a89cb7_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id', ''), _negated=True), fields=('owner', 'source', 'external_id'), name='suggestion_once_per_source_id')],
            },
        ),
    ]
