# Generated by Django 6.1.1 on 2026-09-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0007_suggestions'),
        ('resume', '0003_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='sent_links',
            field=models.ManyToManyField(blank=True, help_text='Portfolios, profiles and videos you pointed them at.', related_name='sent_with', to='resume.link', verbose_name='links sent'),
        ),
    ]
