# Generated by Django 6.1.1 on 2026-09-10 04:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0008_sent_links'),
        ('jobs', '0011_industry_nace'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Which part of the employer this was for, if you know.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='applications', to='jobs.department', verbose_name='department'),
        ),
    ]
