# Generated by Django 6.1.1 on 2026-09-15 13:05

"""One more answer to *applied through*: the employment service's own listings (#202)."""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0009_application_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='channel',
            field=models.CharField(blank=True, choices=[('company_site', 'Company website'), ('job_board', 'Job board'), ('employment_service', 'Employment service'), ('email', 'Email'), ('referral', 'Referral'), ('recruiter', 'Recruiter'), ('event', 'Event or fair'), ('other', 'Other')], max_length=20, verbose_name='applied through'),
        ),
    ]
