# Generated by Django 6.1.1 on 2026-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0014_why_it_ended_referrer_and_agency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationevent',
            name='kind',
            field=models.CharField(choices=[('status_change', 'Status change'), ('note', 'Note'), ('email_sent', 'Email sent'), ('email_received', 'Email received'), ('call', 'Call'), ('interview', 'Interview'), ('interview_scheduled', 'Interview scheduled'), ('interview_cancelled', 'Interview cancelled'), ('assessment', 'Assessment or test'), ('offer', 'Offer received'), ('rejection', 'Rejection received'), ('follow_up', 'Followed up'), ('other', 'Other')], default='note', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='kind',
            field=models.CharField(choices=[('phone', 'Phone screen'), ('video', 'Video call'), ('onsite', 'On site'), ('panel', 'Panel'), ('assessment', 'Assessment or test'), ('other', 'Other')], default='video', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='kind',
            field=models.CharField(choices=[('status_change', 'Status change'), ('note', 'Note'), ('email_sent', 'Email sent'), ('email_received', 'Email received'), ('call', 'Call'), ('interview', 'Interview'), ('interview_scheduled', 'Interview scheduled'), ('interview_cancelled', 'Interview cancelled'), ('assessment', 'Assessment or test'), ('offer', 'Offer received'), ('rejection', 'Rejection received'), ('follow_up', 'Followed up'), ('other', 'Other')], default='note', max_length=20, verbose_name='type'),
        ),
    ]
