# Generated by Django 6.1.1 on 2026-10-03 20:57

import django.db.models.deletion
from django.db import migrations, models


def tie_entries_to_their_interviews(apps, schema_editor):
    """Link what settling wrote to the interview it came from, and name the no-shows (#448).

    The entry holds no word that can be matched across languages, so it is found the way
    the counters used to find it: the same application, dated to the interview's start.
    """
    Interview = apps.get_model("applications", "Interview")
    ApplicationEvent = apps.get_model("applications", "ApplicationEvent")
    for interview in Interview.objects.filter(outcome__in=("done", "no_show")).iterator():
        entries = ApplicationEvent.objects.filter(
            application_id=interview.application_id,
            kind="interview",
            occurred_at=interview.starts_at,
            interview__isnull=True,
        )
        if interview.outcome == "no_show":
            entries.update(kind="interview_no_show", interview=interview)
        else:
            entries.update(interview=interview)


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0015_type_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationevent',
            name='interview',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='applications.interview', verbose_name='interview'),
        ),
        migrations.AlterField(
            model_name='applicationevent',
            name='kind',
            field=models.CharField(choices=[('status_change', 'Status change'), ('note', 'Note'), ('email_sent', 'Email sent'), ('email_received', 'Email received'), ('call', 'Call'), ('interview', 'Interview'), ('interview_scheduled', 'Interview scheduled'), ('interview_cancelled', 'Interview cancelled'), ('interview_no_show', 'Interview no-show'), ('assessment', 'Assessment or test'), ('offer', 'Offer received'), ('rejection', 'Rejection received'), ('follow_up', 'Followed up'), ('other', 'Other')], default='note', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='kind',
            field=models.CharField(choices=[('status_change', 'Status change'), ('note', 'Note'), ('email_sent', 'Email sent'), ('email_received', 'Email received'), ('call', 'Call'), ('interview', 'Interview'), ('interview_scheduled', 'Interview scheduled'), ('interview_cancelled', 'Interview cancelled'), ('interview_no_show', 'Interview no-show'), ('assessment', 'Assessment or test'), ('offer', 'Offer received'), ('rejection', 'Rejection received'), ('follow_up', 'Followed up'), ('other', 'Other')], default='note', max_length=20, verbose_name='type'),
        ),
        migrations.RunPython(tie_entries_to_their_interviews, migrations.RunPython.noop),
    ]
