# Generated by Django 6.1.1 on 2026-10-05 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0016_interview_no_show_and_linked_entries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='channel',
            field=models.CharField(blank=True, choices=[('company_site', 'Company website'), ('job_board', 'Job board'), ('employment_service', 'Public employment service'), ('email', 'Email'), ('referral', 'Referral'), ('recruiter', 'Recruiter'), ('event', 'Event or fair'), ('other', 'Other')], max_length=20, verbose_name='applied through'),
        ),
    ]
