# Generated by Django 6.1.1 on 2026-09-05 16:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('kind', models.CharField(choices=[('notifier', 'notifier'), ('store', 'store'), ('sync', 'sync')], max_length=20, verbose_name='kind')),
                ('plugin', models.CharField(max_length=60, verbose_name='plugin')),
                ('label', models.CharField(help_text='Your name for it: “Telegram”, “Paperless at home”.', max_length=100, verbose_name='label')),
                ('config', models.JSONField(blank=True, default=dict, verbose_name='configuration')),
                ('secrets_encrypted', models.TextField(blank=True, editable=False, verbose_name='secrets')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('last_ok_at', models.DateTimeField(blank=True, null=True, verbose_name='last worked')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'connection',
                'verbose_name_plural': 'connections',
                'ordering': ('kind', 'plugin', 'label'),
                'indexes': [models.Index(fields=['owner', 'kind'], name='plugins_con_owner_i_f1f948_idx')],
            },
        ),
    ]
