# Generated by Django 6.1.1 on 2026-09-06 13:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('plugins', '0001_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='last_summary',
            field=models.TextField(blank=True, verbose_name="last run's report"),
        ),
        migrations.AddField(
            model_name='connection',
            name='synced_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last run'),
        ),
        migrations.CreateModel(
            name='SyncLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.PositiveBigIntegerField()),
                ('remote_href', models.CharField(blank=True, max_length=500, verbose_name='remote address')),
                ('uid', models.CharField(blank=True, max_length=200, verbose_name='identifier')),
                ('etag', models.CharField(blank=True, max_length=200, verbose_name='version tag')),
                ('local_hash', models.CharField(blank=True, max_length=64, verbose_name='last pushed')),
                ('last_synced_at', models.DateTimeField(blank=True, null=True, verbose_name='last synced')),
                ('remote_gone', models.BooleanField(default=False, verbose_name='removed on the other side')),
                ('connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='plugins.connection', verbose_name='connection')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'sync link',
                'verbose_name_plural': 'sync links',
                'indexes': [models.Index(fields=['connection', 'remote_href'], name='plugins_syn_connect_192f6d_idx')],
                'constraints': [models.UniqueConstraint(fields=('connection', 'content_type', 'object_id'), name='synclink_one_per_record')],
            },
        ),
    ]
