# Generated by Django 6.1.1 on 2026-09-07 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_sync_links'),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginRepository',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.SlugField(unique=True, verbose_name='name')),
                ('tier', models.CharField(choices=[('official', 'Official'), ('custom', 'Custom')], default='custom', max_length=10, verbose_name='tier')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='index address')),
                ('public_key', models.CharField(blank=True, help_text='Ed25519, base64. Without it there is no catalogue: an unsigned list of addresses to run code from is not something Postulo will offer.', max_length=200, verbose_name='public key')),
                ('enabled', models.BooleanField(default=True, verbose_name='enabled')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='added')),
            ],
            options={
                'verbose_name': 'plugin repository',
                'verbose_name_plural': 'plugin repositories',
                'ordering': ('tier', 'name'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('tier', 'official')), fields=('tier',), name='one_official_plugin_repository')],
            },
        ),
    ]
