# Generated by Django 6.1.1 on 2026-09-07 17:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0004_seed_plugin_repositories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PluginPolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plugin', models.CharField(max_length=60, verbose_name='plugin')),
                ('state', models.CharField(choices=[('available', 'Available — the person chooses'), ('unavailable', 'Unavailable — not offered at all'), ('on', 'On — and they may not switch it off'), ('off', 'Off — and they may not switch it on')], default='available', max_length=12, verbose_name='state')),
                ('decided_at', models.DateTimeField(auto_now=True, verbose_name='decided')),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='decided by')),
                ('person', models.ForeignKey(blank=True, help_text='Empty for the instance default; an account for an exception to it.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='plugin_policies', to=settings.AUTH_USER_MODEL, verbose_name='person')),
            ],
            options={
                'verbose_name': 'plugin policy',
                'verbose_name_plural': 'plugin policies',
                'ordering': ('plugin', 'person_id'),
                'constraints': [models.UniqueConstraint(fields=('plugin', 'person'), name='one_plugin_policy_per_person'), models.UniqueConstraint(condition=models.Q(('person__isnull', True)), fields=('plugin',), name='one_default_policy_per_plugin')],
            },
        ),
    ]
