# Generated by Django 6.1.1 on 2026-09-09 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_pluginpolicy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='kind',
            field=models.CharField(choices=[('notifier', 'notifier'), ('outbox', 'outbox'), ('store', 'store'), ('sync', 'sync')], max_length=20, verbose_name='kind'),
        ),
    ]
