# Generated by Django 6.1.1 on 2026-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0006_connection_outbox_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connection',
            name='kind',
            field=models.CharField(choices=[('notifier', 'notifier'), ('outbox', 'outbox'), ('store', 'store'), ('sync', 'sync')], max_length=20, verbose_name='type'),
        ),
    ]
