# Generated by Django 6.1.1 on 2026-10-04 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_type_labels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='connection',
            name='last_summary',
        ),
        migrations.AddField(
            model_name='connection',
            name='last_report',
            field=models.JSONField(blank=True, default=dict, verbose_name="last run's report"),
        ),
    ]
