# Generated by Django 6.1.1 on 2026-09-15 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BrowserNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('event', models.CharField(max_length=40, verbose_name='event')),
                ('title', models.CharField(max_length=300, verbose_name='title')),
                ('body', models.TextField(blank=True, verbose_name='body')),
                ('url', models.CharField(blank=True, max_length=500, verbose_name='address')),
                ('shown_at', models.DateTimeField(blank=True, null=True, verbose_name='shown at')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'browser notice',
                'verbose_name_plural': 'browser notices',
                'ordering': ('created_at',),
                'indexes': [models.Index(fields=['owner', 'shown_at'], name='notificatio_owner_i_af807f_idx')],
            },
        ),
    ]
