# Generated by Django 6.1.1 on 2026-09-04 17:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('issuer', models.CharField(blank=True, max_length=200, verbose_name='issued by')),
                ('issued_on', models.DateField(blank=True, null=True, verbose_name='issued on')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='expires on')),
                ('credential_url', models.URLField(blank=True, verbose_name='credential link')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'certification',
                'verbose_name_plural': 'certifications',
                'ordering': ('-issued_on', 'order'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('institution', models.CharField(max_length=200, verbose_name='institution')),
                ('qualification', models.CharField(help_text='For example, “BSc Computer Science”.', max_length=200, verbose_name='qualification')),
                ('field_of_study', models.CharField(blank=True, max_length=200, verbose_name='field of study')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='from')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='until')),
                ('grade', models.CharField(blank=True, max_length=100, verbose_name='grade')),
                ('highlights', models.TextField(blank=True, verbose_name='highlights')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'education',
                'verbose_name_plural': 'education',
                'ordering': ('-end_date', 'order'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('organisation', models.CharField(max_length=200, verbose_name='organisation')),
                ('role', models.CharField(max_length=200, verbose_name='role')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='location')),
                ('start_date', models.DateField(verbose_name='from')),
                ('end_date', models.DateField(blank=True, help_text='Leave empty if this is your current role.', null=True, verbose_name='until')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('highlights', models.TextField(blank=True, help_text='One achievement per line.', verbose_name='highlights')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'experience',
                'verbose_name_plural': 'experience',
                'ordering': ('-start_date', 'order'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LanguageSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='language')),
                ('proficiency', models.CharField(choices=[('a1', 'A1 — beginner'), ('a2', 'A2 — elementary'), ('b1', 'B1 — intermediate'), ('b2', 'B2 — upper intermediate'), ('c1', 'C1 — advanced'), ('c2', 'C2 — proficient'), ('native', 'Native')], default='b2', max_length=10, verbose_name='proficiency')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'language',
                'verbose_name_plural': 'languages',
                'ordering': ('order', '-pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('role', models.CharField(blank=True, max_length=200, verbose_name='your role')),
                ('url', models.URLField(blank=True, verbose_name='link')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='from')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='until')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('highlights', models.TextField(blank=True, verbose_name='highlights')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
                'ordering': ('order', '-pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SkillGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'skill group',
                'verbose_name_plural': 'skill groups',
                'ordering': ('order', '-pk'),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='resume.skillgroup', verbose_name='group')),
            ],
            options={
                'verbose_name': 'skill',
                'verbose_name_plural': 'skills',
                'ordering': ('order', '-pk'),
                'abstract': False,
            },
        ),
    ]
