# Generated by Django 6.1.1 on 2026-09-04 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='languageskill',
            options={'ordering': ('order', 'pk'), 'verbose_name': 'language', 'verbose_name_plural': 'languages'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order', 'pk'), 'verbose_name': 'project', 'verbose_name_plural': 'projects'},
        ),
        migrations.AlterModelOptions(
            name='skill',
            options={'ordering': ('order', 'pk'), 'verbose_name': 'skill', 'verbose_name_plural': 'skills'},
        ),
        migrations.AlterModelOptions(
            name='skillgroup',
            options={'ordering': ('order', 'pk'), 'verbose_name': 'skill group', 'verbose_name_plural': 'skill groups'},
        ),
    ]
