# Generated by Django 6.1.1 on 2026-09-06 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_languageskill_options_alter_project_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('url', models.URLField(max_length=500, verbose_name='address')),
                ('kind', models.CharField(choices=[('portfolio', 'Portfolio'), ('site', 'Personal site'), ('code', 'Code (GitHub, GitLab…)'), ('design', 'Design (Behance, Dribbble…)'), ('publication', 'Publication'), ('video', 'Video'), ('other', 'Other')], default='portfolio', max_length=20, verbose_name='kind')),
                ('description', models.CharField(blank=True, help_text='One line, for whoever is reading the CV.', max_length=250, verbose_name='description')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='last checked')),
                ('check_status', models.CharField(blank=True, choices=[('', 'Not checked'), ('ok', 'Answered'), ('broken', 'Did not answer')], default='', max_length=10, verbose_name='last check')),
                ('check_detail', models.CharField(blank=True, max_length=250, verbose_name='what the check found')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'link',
                'verbose_name_plural': 'links',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
    ]
