# Generated by Django 6.1.1 on 2026-09-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0006_a_level_can_be_unstated'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='esco_uri',
            field=models.CharField(blank=True, editable=False, max_length=200, verbose_name='ESCO skill'),
        ),
    ]
