# Generated by Django 6.1.1 on 2026-10-03 17:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('resume', '0008_a_language_is_a_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='kind',
            field=models.CharField(choices=[('portfolio', 'Portfolio'), ('site', 'Personal site'), ('code', 'Code (GitHub, GitLab…)'), ('design', 'Design (Behance, Dribbble…)'), ('publication', 'Publication'), ('video', 'Video'), ('other', 'Other')], default='portfolio', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='type of entry'),
        ),
    ]
