# Generated by Django 6.1.1 on 2026-10-06 08:23

import django.db.models.deletion
import postulo.core.language_field
import postulo.resume.publications
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_type_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('entry_type', models.CharField(choices=[('article', 'Journal article'), ('inproceedings', 'Paper in proceedings'), ('book', 'Book'), ('inbook', 'Part of a book'), ('incollection', 'Chapter in a collection'), ('proceedings', 'Proceedings'), ('phdthesis', 'PhD thesis'), ('mastersthesis', "Master's thesis"), ('techreport', 'Technical report'), ('manual', 'Manual'), ('booklet', 'Booklet'), ('unpublished', 'Unpublished'), ('online', 'Online'), ('dataset', 'Dataset'), ('software', 'Software'), ('misc', 'Other')], default='article', max_length=20, verbose_name='type')),
                ('title', models.CharField(max_length=500, verbose_name='title')),
                ('authors', models.TextField(blank=True, max_length=2000, verbose_name='authors')),
                ('editors', models.TextField(blank=True, max_length=2000, verbose_name='editors')),
                ('container_title', models.CharField(blank=True, max_length=300, verbose_name='published in')),
                ('publisher', models.CharField(blank=True, max_length=200, verbose_name='publisher')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='institution')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='place')),
                ('date', models.CharField(blank=True, max_length=10, validators=[postulo.resume.publications.validate_date], verbose_name='date')),
                ('volume', models.CharField(blank=True, max_length=40, verbose_name='volume')),
                ('number', models.CharField(blank=True, max_length=40, verbose_name='number')),
                ('pages', models.CharField(blank=True, max_length=40, verbose_name='pages')),
                ('edition', models.CharField(blank=True, max_length=40, verbose_name='edition')),
                ('series', models.CharField(blank=True, max_length=200, verbose_name='series')),
                ('chapter', models.CharField(blank=True, max_length=40, verbose_name='chapter')),
                ('doi', models.CharField(blank=True, max_length=200, validators=[postulo.resume.publications.validate_doi], verbose_name='DOI')),
                ('url', models.URLField(blank=True, max_length=500, verbose_name='link')),
                ('note', models.CharField(blank=True, max_length=500, verbose_name='note')),
                ('language', postulo.core.language_field.LanguageField(blank=True, max_length=35, verbose_name='language')),
                ('cite_key', models.CharField(blank=True, max_length=80, validators=[postulo.resume.publications.validate_cite_key], verbose_name='citation key')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'ordering': ('order', 'pk'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('cite_key', ''), _negated=True), fields=('owner', 'cite_key'), name='resume_one_cite_key_per_owner')],
            },
        ),
    ]
