# Generated by Django 6.1.1 on 2026-10-06 08:15

import django.db.models.deletion
from django.db import migrations, models


def link_where_one_company_has_the_name(apps, schema_editor):
    """Link an entry to the company of the same owner that has its name, where there is one.

    Never adds a company and never guesses: two companies of one name key cannot exist (the
    column is unique per owner), so "exactly one" is "any", and an entry whose name matches
    nothing stays unlinked (#683).
    """
    from postulo.core.slugs import name_key

    Company = apps.get_model("jobs", "Company")
    Experience = apps.get_model("resume", "Experience")
    keys = {}
    for owner_id, key, pk in Company.objects.values_list("owner_id", "name_key", "pk"):
        keys[(owner_id, key)] = pk
    for entry in Experience.objects.filter(company__isnull=True).only("pk", "owner_id", "organisation"):
        pk = keys.get((entry.owner_id, name_key(entry.organisation)))
        if pk is not None:
            Experience.objects.filter(pk=entry.pk).update(company_id=pk)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_company_from_career'),
        ('resume', '0009_type_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='company',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='career_entries', to='jobs.company', verbose_name='company'),
        ),
        migrations.RunPython(link_where_one_company_has_the_name, migrations.RunPython.noop),
    ]
