# Generated by Django 6.1.1 on 2026-10-06 08:29

import postulo.core.language_field
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0009_type_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='languageskill',
            name='code',
            field=postulo.core.language_field.LanguageField(blank=True, max_length=35, verbose_name='language code'),
        ),
    ]
