# Generated by Django 6.1.1 on 2026-10-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_experience_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='eqf_level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(None, 'Not stated'), (1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5'), (6, 'Level 6'), (7, 'Level 7'), (8, 'Level 8')], null=True, verbose_name='EQF level'),
        ),
    ]
