# Generated by Django 6.1.1 on 2026-10-06 15:55

import django.db.models.deletion
from django.db import migrations, models


def link_where_a_company_has_the_name(apps, schema_editor):
    """Link a certification to the company of the same owner that has its issuer's name.

    Never adds a company and never guesses: the name is unique per owner, so "exactly one"
    is "any", and an issuer that matches nothing (or is blank) stays text (#686).
    """
    from postulo.core.slugs import name_key

    Company = apps.get_model("jobs", "Company")
    Certification = apps.get_model("resume", "Certification")
    keys = {}
    for owner_id, key, pk in Company.objects.values_list("owner_id", "name_key", "pk"):
        keys[(owner_id, key)] = pk
    for entry in Certification.objects.filter(company__isnull=True).exclude(issuer="").only(
        "pk", "owner_id", "issuer"
    ):
        pk = keys.get((entry.owner_id, name_key(entry.issuer)))
        if pk is not None:
            Certification.objects.filter(pk=entry.pk).update(company_id=pk)


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_company_from_career'),
        ('resume', '0016_education_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='certification',
            name='company',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='jobs.company', verbose_name='company'),
        ),
        migrations.RunPython(link_where_a_company_has_the_name, migrations.RunPython.noop),
    ]
