# Generated by Django 6.1.1 on 2026-10-06 15:58

import django.db.models.deletion
import postulo.core.personal
import postulo.resume.driving
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0017_certification_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DrivingLicence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('country', models.CharField(blank=True, max_length=2, validators=[postulo.core.personal.validate_country_code], verbose_name='country')),
                ('categories', models.JSONField(blank=True, default=list, validators=[postulo.resume.driving.validate], verbose_name='categories')),
                ('other_categories', models.CharField(blank=True, max_length=100, verbose_name='other categories')),
                ('first_issued_on', models.DateField(blank=True, null=True, verbose_name='first issued on')),
                ('expires_on', models.DateField(blank=True, null=True, verbose_name='expires on')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'driving licence',
                'verbose_name_plural': 'driving licences',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
    ]
