# Generated by Django 6.1.1 on 2026-10-06 22:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0018_driving_categories'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Honour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('awarded_by', models.CharField(blank=True, max_length=200, verbose_name='awarded by')),
                ('awarded_on', models.DateField(blank=True, null=True, verbose_name='awarded on')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('url', models.URLField(blank=True, verbose_name='link')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'honour or award',
                'verbose_name_plural': 'honours and awards',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
    ]
