# Generated by Django 6.1.1 on 2026-10-06 22:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0021_honour_and_membership_companies'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('provider', models.CharField(blank=True, max_length=200, verbose_name='provider')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='from')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='until')),
                ('hours', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='hours')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('url', models.URLField(blank=True, verbose_name='link')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'course',
                'verbose_name_plural': 'courses',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
    ]
