# Generated by Django 6.1.1 on 2026-10-06 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_capture_goes_with_its_listing'),
        ('resume', '0022_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='company',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='jobs.company', verbose_name='company'),
        ),
    ]
