# Generated by Django 6.1.1 on 2026-10-06 22:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_capture_goes_with_its_listing'),
        ('resume', '0023_course_company'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('relationship', models.CharField(blank=True, help_text='How they know your work, as a CV should say it: “Line manager at Aperture, 2019 to 2022”.', max_length=200, verbose_name='relationship')),
                ('permission', models.CharField(choices=[('not_asked', 'Not asked'), ('asked', 'Asked'), ('agreed', 'Agreed')], default='not_asked', help_text='Your own note of whether they have said yes. A CV prints a reference only when this is Agreed.', max_length=10, verbose_name='permission')),
                ('show_details', models.BooleanField(default=False, help_text='Off prints the name, the role and the relationship, and no way to reach them.', verbose_name='print their email address and telephone number')),
                ('note', models.TextField(blank=True, help_text='Yours. It is never printed on a document.', verbose_name='note')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_references', to='jobs.contact', verbose_name='person')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'reference',
                'verbose_name_plural': 'references',
                'ordering': ('order', 'pk'),
                'abstract': False,
                'constraints': [models.UniqueConstraint(fields=('owner', 'contact'), name='resume_one_reference_per_contact', violation_error_message='This person is already one of your references.')],
            },
        ),
    ]
