# Generated by Django 6.1.1 on 2026-10-07 02:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0024_references'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.PositiveIntegerField(default=0, help_text='Lower numbers appear first.', verbose_name='order')),
                ('event', models.CharField(max_length=200, verbose_name='event')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='what you presented')),
                ('role', models.CharField(blank=True, choices=[('', 'Not stated'), ('speaker', 'Speaker'), ('poster', 'Poster presenter'), ('panellist', 'Panellist'), ('workshop', 'Workshop leader'), ('organiser', 'Organiser'), ('committee', 'Committee member'), ('attendee', 'Attendee')], default='', max_length=12, verbose_name='your role')),
                ('kind', models.CharField(blank=True, choices=[('', 'Not stated'), ('conference', 'Conference'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('other', 'Other')], default='', max_length=12, verbose_name='type')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='from')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='until')),
                ('place', models.CharField(blank=True, max_length=200, verbose_name='place')),
                ('url', models.URLField(blank=True, verbose_name='link')),
                ('summary', models.TextField(blank=True, verbose_name='summary')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'event',
                'verbose_name_plural': 'events',
                'ordering': ('order', 'pk'),
                'abstract': False,
            },
        ),
    ]
