# Generated by Django 6.1.1 on 2026-09-04 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaptureToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='Which device or tool this is for.', max_length=100, verbose_name='name')),
                ('prefix', models.CharField(editable=False, max_length=8, verbose_name='prefix')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='token hash')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last used')),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='revoked')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'capture token',
                'verbose_name_plural': 'capture tokens',
                'ordering': ('-created_at',),
            },
        ),
    ]
