# Generated by Django 6.1.1 on 2026-09-16 09:18

import django.db.models.deletion
import postulo.api.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_apitoken_scopes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('key', models.CharField(editable=False, max_length=200, verbose_name='key')),
                ('fingerprint', models.CharField(editable=False, max_length=64, verbose_name='fingerprint')),
                ('status_code', models.PositiveSmallIntegerField(default=0, verbose_name='status')),
                ('body', models.JSONField(blank=True, default=dict, encoder=postulo.api.models.AnswerEncoder, verbose_name='answer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'idempotent request',
                'verbose_name_plural': 'idempotent requests',
                'ordering': ('-created_at',),
                'constraints': [models.UniqueConstraint(fields=('owner', 'key'), name='unique_idempotency_key_per_owner')],
            },
        ),
    ]
