"""The throwaway model needs a migration, or the suite cannot build a PostgreSQL (#219).

An app with no migrations is created in `migrate`'s syncdb phase, which runs **before** any
migration does -- so `testapp_widget` was built first and its foreign key pointed at an
`accounts_user` that did not exist yet. SQLite records such a key and checks it later, so
nothing ever complained; PostgreSQL refuses the ALTER TABLE outright, and every test that
touched the database errored at setup. A migration moves this app into the ordered phase,
after the one it depends on, which is where a model with a foreign key belongs.
"""

# Generated by Django 6.1.1 on 2026-09-16 07:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Widget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
        ),
    ]
