// Copy the marks listed in assets/brands.txt from the simple-icons package into the
// static directory, and write the notice beside them (#654). Like the icons, the result
// is committed: Node is needed to change the set, never to run the application.
//
// Exits non-zero on a slug the package no longer has (an upstream removal is a decision at
// the bump, never silent), and on a mark whose own licence entry is outside
// assets/brand-terms.txt.
//
// Each mark is copied unmodified except for one thing: Simple Icons ships it with no fill,
// and its published colour is only in the data, so the colour is written onto the root as
// a `fill`. That is the mark drawn in its owner's colour, which is the one mode Postulo
// allows ("brand", TRADEMARKS.md rule 2); NOTICE.txt records it.

import { copyFileSync, existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const LIST = "assets/brands.txt";
const LICENCES = "assets/brand-terms.txt";
const PACKAGE = "node_modules/simple-icons";
const DESTINATION = "src/postulo/static/brands";

const lines = (path) =>
  readFileSync(path, "utf8")
    .split(/\r?\n/)
    .map((line) => line.replace(/#.*/, "").trim())
    .filter(Boolean);

const wanted = lines(LIST);
const allowed = new Set(lines(LICENCES));

if (!existsSync(PACKAGE)) {
  console.error(`${PACKAGE} is missing; run "npm ci" first.`);
  process.exit(1);
}

const version = JSON.parse(readFileSync(join(PACKAGE, "package.json"), "utf8")).version;
const data = new Map(
  JSON.parse(readFileSync(join(PACKAGE, "data", "simple-icons.json"), "utf8")).map((entry) => [entry.slug, entry]),
);

mkdirSync(DESTINATION, { recursive: true });

let failed = false;
const notices = [];
for (const slug of [...wanted].sort()) {
  const entry = data.get(slug);
  const from = join(PACKAGE, "icons", `${slug}.svg`);
  if (!entry || !existsSync(from)) {
    console.error(`simple-icons ${version} has no mark named "${slug}": removed upstream? Read the removals, then drop it from ${LIST}.`);
    failed = true;
    continue;
  }
  const licence = entry.license ? entry.license.type : "";
  if (licence && !allowed.has(licence)) {
    console.error(`"${slug}" carries the licence "${licence}", which is not in ${LICENCES}.`);
    failed = true;
    continue;
  }
  const colour = `#${entry.hex.toUpperCase()}`;
  // One trailing newline, as the repository's end-of-file hook leaves every file.
  const svg = readFileSync(from, "utf8")
    .replace(/^<svg\b/, `<svg fill="${colour}"`)
    .replace(/\s*$/, "\n");
  writeFileSync(join(DESTINATION, `${slug}.svg`), svg);
  notices.push(
    [
      `${slug}`,
      `  Owner: ${entry.title}`,
      `  Mode: brand (the published colour ${colour}, unmodified; it clears 3:1 on the light and the dark page)`,
      `  Licence: ${licence || "none declared for the artwork; the mark itself is its owner's"}`,
      `  Source: ${entry.source || "not stated"}`,
      `  Guidelines: ${entry.guidelines || "not stated"}`,
    ].join("\n"),
  );
}

for (const file of readdirSync(DESTINATION)) {
  if (file.endsWith(".svg") && !wanted.includes(file.slice(0, -4))) {
    rmSync(join(DESTINATION, file));
    console.log(`removed ${file}: not in ${LIST}`);
  }
}

if (failed) {
  process.exit(1);
}

const header = `Brand marks in this directory
=============================

Each file is a logo that belongs to the owner named below, taken from the Simple Icons
package (simple-icons ${version}, https://simpleicons.org, whose own artwork notice is
CC0-1.0). Postulo shows a mark only to identify the service it stands for, and claims no
endorsement by, or involvement of, its owner: the owners are not involved with Postulo.

These files are NOT covered by Postulo's AGPL-3.0-or-later licence, which cannot speak for
somebody else's trademark. They are used unmodified in the one mode recorded for each mark
(its published colour), under the rule in TRADEMARKS.md. If you own one of these marks and
would rather it were not used, write to tiago.agueda@tiagoagueda.com and it will be changed.

Where a mark carries a licence of its own, it is named; CC-BY-4.0 and CC-BY-SA-4.0 ask for
attribution, which is this notice, and the second asks that the artwork stay under the same
terms.

Generated by scripts/sync-brands.mjs from assets/brands.txt. Do not edit by hand.

`;
writeFileSync(join(DESTINATION, "NOTICE.txt"), header + notices.join("\n\n") + "\n");
console.log(`${wanted.length} brand marks in ${DESTINATION}`);
