# Generated by Django 6.1.1 on 2026-09-04 16:59

import django.db.models.deletion
import postulo.accounts.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default=postulo.accounts.models.generate_invite_token, editable=False, max_length=64, unique=True, verbose_name='token')),
                ('email', models.EmailField(blank=True, help_text='Optional. If set, only this address may use the invitation.', max_length=254, verbose_name='email address')),
                ('note', models.CharField(blank=True, help_text='A reminder of who this is for.', max_length=200, verbose_name='note')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(default=postulo.accounts.models.default_invite_expiry, verbose_name='expires at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('accepted_by', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invite_used', to=settings.AUTH_USER_MODEL, verbose_name='accepted by')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invites_created', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'invitation',
                'verbose_name_plural': 'invitations',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headline', models.CharField(blank=True, help_text='A short professional title, such as “Backend engineer”.', max_length=200, verbose_name='headline')),
                ('phone', models.CharField(blank=True, max_length=40, verbose_name='phone')),
                ('location', models.CharField(blank=True, help_text='City and country, as it should appear on a CV.', max_length=120, verbose_name='location')),
                ('website', models.URLField(blank=True, verbose_name='website')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('source_repo_url', models.URLField(blank=True, help_text='A profile on GitHub, Forgejo, GitLab or similar.', verbose_name='code repository')),
                ('language', models.CharField(blank=True, max_length=10, verbose_name='language')),
                ('time_zone', models.CharField(blank=True, max_length=64, verbose_name='time zone')),
                ('theme', models.CharField(choices=[('system', 'Match the operating system'), ('light', 'Light'), ('dark', 'Dark')], default='system', max_length=10, verbose_name='theme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'profile',
                'verbose_name_plural': 'profiles',
            },
        ),
    ]
