# Generated by Django 6.1.1 on 2026-09-05 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_username_and_verified_addresses'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='table_settings',
            field=models.JSONField(blank=True, default=dict, verbose_name='table settings'),
        ),
    ]
