# Generated by Django 6.1.1 on 2026-09-05 17:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile_table_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='quiet_after_days',
            field=models.PositiveSmallIntegerField(default=21, help_text='Days without anything happening, and nothing planned, before Postulo asks.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='quiet after'),
        ),
    ]
