# Generated by Django 6.1.1 on 2026-09-05 18:20

import postulo.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_quiet_after_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=postulo.accounts.models.upload_to_avatars, verbose_name='picture'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gravatar_checked_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Gravatar checked on'),
        ),
        migrations.AddField(
            model_name='profile',
            name='gravatar_image',
            field=models.ImageField(blank=True, editable=False, upload_to=postulo.accounts.models.upload_to_avatars, verbose_name='Gravatar copy'),
        ),
        migrations.AddField(
            model_name='profile',
            name='use_gravatar',
            field=models.BooleanField(default=False, verbose_name='use my Gravatar'),
        ),
    ]
