# Generated by Django 6.1.1 on 2026-09-06 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hidden_nav_items',
            field=models.JSONField(blank=True, default=list, verbose_name='hidden navigation items'),
        ),
    ]
