# Generated by Django 6.1.1 on 2026-09-06 19:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_hidden_nav_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheme', models.CharField(choices=[('orcid', 'ORCID'), ('researcherid', 'ResearcherID'), ('scopus', 'Scopus Author ID'), ('isni', 'ISNI'), ('other', 'Other')], max_length=20, verbose_name='scheme')),
                ('value', models.CharField(max_length=100, verbose_name='identifier')),
                ('label', models.CharField(blank=True, help_text='What the identifier is, when the scheme is Other.', max_length=60, verbose_name='name')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='accounts.profile', verbose_name='profile')),
            ],
            options={
                'verbose_name': 'identifier',
                'verbose_name_plural': 'identifiers',
                'ordering': ('scheme', 'value'),
                'constraints': [models.UniqueConstraint(condition=models.Q(('scheme', 'other'), _negated=True), fields=('profile', 'scheme'), name='one_identifier_per_scheme_per_person')],
            },
        ),
    ]
