# Generated by Django 6.1.1 on 2026-09-06 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_person_identifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dashboard_widgets',
            field=models.JSONField(blank=True, default=None, null=True, verbose_name='dashboard widgets'),
        ),
    ]
