# Generated by Django 6.1.1 on 2026-09-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_profile_dashboard_widgets'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='plugins_off',
            field=models.JSONField(blank=True, default=list, verbose_name='plugins switched off'),
        ),
    ]
