# Generated by Django 6.1.1 on 2026-09-08 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_carry_phone_numbers_across"),
        ('accounts', '0010_profile_plugins_off'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
