# Generated by Django 6.1.1 on 2026-09-09 15:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_profile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecoveryLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_fingerprint', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(verbose_name='expires at')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='used at')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='revoked at')),
                ('issued_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='issued by')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_links', to=settings.AUTH_USER_MODEL, verbose_name='person')),
            ],
            options={
                'verbose_name': 'recovery link',
                'verbose_name_plural': 'recovery links',
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['person', '-created_at'], name='accounts_re_person__333cca_idx')],
            },
        ),
    ]
