# Generated by Django 6.1.1 on 2026-09-15 14:45

"""Whether an entry's form on Your career shows its order number: off, since the arrows on the
overview are the control; on for somebody who cannot use them or would rather type (#203).
"""

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_forget_choices_about_shipped_plugins'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='show_career_order',
            field=models.BooleanField(default=False, verbose_name='show the order number on career entries'),
        ),
    ]
