# Generated by Django 6.1.1 on 2026-09-28 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_closing_soon_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='keep_page_rendering',
            field=models.BooleanField(default=False, verbose_name='keep a rendering of a captured page'),
        ),
        migrations.AddField(
            model_name='profile',
            name='keep_page_source',
            field=models.BooleanField(default=False, verbose_name='keep the source of a captured page'),
        ),
    ]
