# Generated by Django 6.1.1 on 2026-10-05 11:34

import postulo.core.personal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_a_language_is_a_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='birth_country',
            field=models.CharField(blank=True, max_length=2, validators=[postulo.core.personal.validate_country_code], verbose_name='country of birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_date',
            field=models.CharField(blank=True, max_length=10, validators=[postulo.core.personal.validate_birth_date], verbose_name='date of birth'),
        ),
        migrations.AddField(
            model_name='profile',
            name='birth_place',
            field=models.CharField(blank=True, max_length=120, verbose_name='place of birth'),
        ),
    ]
