# Generated by Django 6.1.1 on 2026-10-05 11:53

import postulo.core.personal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_profile_date_and_place_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='nationalities',
            field=models.JSONField(blank=True, default=list, validators=[postulo.core.personal.validate_nationalities], verbose_name='nationalities'),
        ),
        migrations.AddField(
            model_name='profile',
            name='nationality_scope',
            field=models.CharField(blank=True, choices=[('eu', 'Citizen of an EU or EEA country, or of Switzerland'), ('other', 'Citizen of another country')], max_length=5, verbose_name='nationality scope'),
        ),
    ]
