# Generated by Django 6.1.1 on 2026-10-05 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_profile_show_key_hints'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='hidden_identifiers',
            field=models.JSONField(blank=True, default=list, verbose_name='hidden identifiers'),
        ),
        migrations.AddField(
            model_name='profile',
            name='identifier_order',
            field=models.JSONField(blank=True, default=list, verbose_name='identifier order'),
        ),
    ]
