# Generated by Django 6.1.1 on 2026-10-05 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_identifier_arrangement'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='save_as_you_go',
            field=models.BooleanField(default=False, verbose_name='save as I go'),
        ),
    ]
