# Generated by Django 6.1.1 on 2026-10-06 16:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_profile_save_as_you_go'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_avatar',
            field=models.BooleanField(default=False, editable=False, verbose_name='has an uploaded picture'),
        ),
        migrations.AddField(
            model_name='profile',
            name='has_gravatar_copy',
            field=models.BooleanField(default=False, editable=False, verbose_name='has a Gravatar copy'),
        ),
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.BinaryField(verbose_name='picture')),
                ('media_type', models.CharField(editable=False, max_length=40, verbose_name='media type')),
                ('stored_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='stored at')),
                ('kind', models.CharField(choices=[('upload', 'Uploaded'), ('gravatar', 'From Gravatar')], max_length=10, verbose_name='Type')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='accounts.profile')),
            ],
            options={
                'verbose_name': 'profile picture',
                'verbose_name_plural': 'profile pictures',
                'constraints': [models.UniqueConstraint(fields=('profile', 'kind'), name='one_picture_of_each_kind')],
            },
        ),
    ]
