# Generated by Django 6.1.1 on 2026-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_move_pictures_into_the_database'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='has_cv_photo',
            field=models.BooleanField(default=False, editable=False, verbose_name='has a CV photo'),
        ),
        migrations.AlterField(
            model_name='profilepicture',
            name='kind',
            field=models.CharField(choices=[('upload', 'Uploaded'), ('gravatar', 'From Gravatar'), ('cv', 'CV photo')], max_length=10, verbose_name='Type'),
        ),
    ]
