# Generated by Django 6.1.1 on 2026-09-04 17:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=60, verbose_name='name')),
                ('slug', models.SlugField(max_length=60, verbose_name='slug')),
                ('colour', models.CharField(blank=True, help_text='A hint for the interface, such as “amber” or “sky”.', max_length=20, verbose_name='colour')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'tag',
                'verbose_name_plural': 'tags',
                'ordering': ('name',),
                'constraints': [models.UniqueConstraint(fields=('owner', 'slug'), name='unique_tag_slug_per_owner')],
            },
        ),
    ]
