# Generated by Django 6.1.1 on 2026-09-05 16:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_name', models.CharField(default='Postulo', help_text='Shown in the header and on the sign-in page.', max_length=60, verbose_name='instance name')),
                ('tagline', models.CharField(blank=True, help_text='A line under the name on the sign-in page. Optional.', max_length=200, verbose_name='tagline')),
                ('registration_open', models.BooleanField(blank=True, help_text='Whether anyone who finds the address may create an account.', null=True, verbose_name='registration open')),
                ('capture_ignore_robots', models.BooleanField(blank=True, null=True, verbose_name='ignore robots.txt when capturing')),
                ('default_language', models.CharField(blank=True, max_length=10, verbose_name='default language')),
                ('default_time_zone', models.CharField(blank=True, max_length=64, verbose_name='default time zone')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='updated by')),
            ],
            options={
                'verbose_name': 'site settings',
                'verbose_name_plural': 'site settings',
            },
        ),
    ]
