# Generated by Django 6.1.1 on 2026-09-06 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_cache_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sso_is_second_factor',
            field=models.BooleanField(blank=True, help_text='Whether somebody who arrived through the identity provider is asked for a code as well.', null=True, verbose_name='single sign-on counts as the second factor'),
        ),
    ]
