# Generated by Django 6.1.1 on 2026-09-07 20:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_sso_second_factor'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_from',
            field=models.EmailField(blank=True, max_length=254, verbose_name='from address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_host',
            field=models.CharField(blank=True, max_length=255, verbose_name='SMTP server'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_password_encrypted',
            field=models.TextField(blank=True, verbose_name='password'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_port',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)], verbose_name='port'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_timeout',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(300)], verbose_name='timeout in seconds'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_use_tls',
            field=models.BooleanField(blank=True, null=True, verbose_name='STARTTLS'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_username',
            field=models.CharField(blank=True, max_length=255, verbose_name='username'),
        ),
    ]
