# Generated by Django 6.1.1 on 2026-09-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_email_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_transport',
            field=models.CharField(blank=True, max_length=60, verbose_name='mail transport'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='transport_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='transport configuration'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='transport_secrets_encrypted',
            field=models.TextField(blank=True, editable=False, verbose_name='transport secrets'),
        ),
    ]
