# Generated by Django 6.1.1 on 2026-09-08 18:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0006_mail_transport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.PositiveBigIntegerField()),
                ('kind', models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('work', 'Work'), ('home', 'Home'), ('switchboard', 'Switchboard'), ('fax', 'Fax'), ('other', 'Other')], max_length=20, verbose_name='kind')),
                ('label', models.CharField(blank=True, help_text='Your name for it, when none of the kinds above fits.', max_length=60, verbose_name='name, if Other')),
                ('number', models.CharField(max_length=40, verbose_name='phone')),
                ('normalised', models.CharField(blank=True, db_index=True, max_length=40)),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'telephone number',
                'verbose_name_plural': 'telephone numbers',
                'ordering': ('-is_primary', 'created_at', 'pk'),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_phonen_content_f30d03_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('content_type', 'object_id'), name='one_primary_phone_number_per_holder'), models.UniqueConstraint(condition=models.Q(('normalised', ''), _negated=True), fields=('normalised',), name='phone_number_unique_across_the_instance')],
            },
        ),
    ]
