# Generated by Django 6.1.1 on 2026-09-09 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_carry_phone_numbers_across'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='offered_languages',
            field=models.JSONField(blank=True, default=list, verbose_name='languages offered'),
        ),
    ]
