# Generated by Django 6.1.1 on 2026-09-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sitesettings_offered_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mail_failures',
            field=models.PositiveIntegerField(default=0, verbose_name='mail failures in a row'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_last_error',
            field=models.TextField(blank=True, verbose_name="mail's last error"),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_last_error_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='mail last failed'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_last_ok_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='mail last worked'),
        ),
    ]
