# Generated by Django 6.1.1 on 2026-09-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_phone_number_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='text_config',
            field=models.JSONField(blank=True, default=dict, verbose_name='text configuration'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_secrets_encrypted',
            field=models.TextField(blank=True, editable=False, verbose_name='text secrets'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='text_transport',
            field=models.CharField(blank=True, max_length=60, verbose_name='text transport'),
        ),
    ]
