# Generated by Django 6.1.1 on 2026-09-09 15:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0013_text_transport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='is_recovery',
            field=models.BooleanField(default=False, verbose_name='way back into the account'),
        ),
        migrations.AddConstraint(
            model_name='phonenumber',
            constraint=models.UniqueConstraint(condition=models.Q(('is_recovery', True)), fields=('owner',), name='one_recovery_number_per_account'),
        ),
    ]
