# Generated by Django 6.1.1 on 2026-09-09 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_recovery_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_sign_in',
            field=models.BooleanField(blank=True, help_text="Offered only while this instance's mail is actually getting through.", null=True, verbose_name='sign in with a code sent by email'),
        ),
    ]
