# Generated by Django 6.1.1 on 2026-09-09 20:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0015_email_sign_in'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PostalAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.PositiveBigIntegerField()),
                ('kind', models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), ('postal', 'Postal'), ('other', 'Other')], max_length=20, verbose_name='kind')),
                ('label', models.CharField(blank=True, help_text='Your name for it, when none of the kinds above fits.', max_length=60, verbose_name='name, if Other')),
                ('street', models.TextField(blank=True, verbose_name='address')),
                ('postcode', models.CharField(blank=True, max_length=20, verbose_name='postcode')),
                ('municipality', models.CharField(blank=True, max_length=120, verbose_name='town or city')),
                ('region', models.CharField(blank=True, max_length=120, verbose_name='region')),
                ('country', models.CharField(blank=True, max_length=2, verbose_name='country')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
                ('comparable', models.CharField(blank=True, db_index=True, max_length=300)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'postal address',
                'verbose_name_plural': 'postal addresses',
                'ordering': ('-is_primary', 'created_at', 'pk'),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_postal_content_8b35f5_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('content_type', 'object_id'), name='one_primary_address_per_holder'), models.UniqueConstraint(condition=models.Q(('comparable', ''), _negated=True), fields=('owner', 'comparable'), name='address_unique_per_owner')],
            },
        ),
    ]
