# Generated by Django 6.1.1 on 2026-09-10 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_postal_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='email_auth',
            field=models.CharField(blank=True, choices=[('password', 'A password, or an app password'), ('xoauth2', 'XOAUTH2, with a token from the provider')], max_length=10, verbose_name='authentication'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_oauth_client_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='client ID'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_oauth_grant',
            field=models.CharField(blank=True, choices=[('mailbox', 'Signed in once, as the mailbox that sends'), ('application', 'The application sends on its own')], max_length=20, verbose_name='grant'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_oauth_provider',
            field=models.CharField(blank=True, max_length=20, verbose_name='identity provider'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_oauth_secrets_encrypted',
            field=models.TextField(blank=True, editable=False, verbose_name='mail OAuth secrets'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_oauth_tenant',
            field=models.CharField(blank=True, max_length=100, verbose_name='directory (tenant) ID'),
        ),
    ]
