# Generated by Django 6.1.1 on 2026-09-12 19:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0017_sitesettings_email_auth_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WebLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.PositiveBigIntegerField()),
                ('kind', models.CharField(choices=[('social', 'Social profile'), ('repository', 'Code repository'), ('website', 'Website')], max_length=20, verbose_name='kind')),
                ('label', models.CharField(blank=True, help_text='LinkedIn, Codeberg, a blog — what to call it. Left blank, the host is shown.', max_length=60, verbose_name='name')),
                ('url', models.URLField(max_length=500, verbose_name='address')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'web link',
                'verbose_name_plural': 'web links',
                'ordering': ('-is_primary', 'created_at', 'pk'),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_weblin_content_2485d3_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('content_type', 'object_id', 'kind'), name='one_primary_web_link_per_holder_and_kind'), models.UniqueConstraint(fields=('content_type', 'object_id', 'url'), name='web_link_unique_per_holder')],
            },
        ),
    ]
