# Generated by Django 6.1.1 on 2026-09-25 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_tag_colour_and_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='privacy_notice',
            field=models.TextField(blank=True, help_text='Shown wherever the site keeps something about another person.', verbose_name='privacy notice'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='retention_days',
            field=models.PositiveIntegerField(blank=True, help_text='Blank keeps them for as long as the instance exists.', null=True, verbose_name='records about other people are kept for (days)'),
        ),
    ]
