# Generated by Django 6.1.1 on 2026-09-28 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_gdpr_retention_and_notice'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='capture_keep_rendering',
            field=models.BooleanField(blank=True, null=True, verbose_name='keep a rendering of a captured page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='capture_keep_source',
            field=models.BooleanField(blank=True, null=True, verbose_name='keep the source of a captured page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='capture_rendering_max_mb',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='largest rendering kept, in megabytes'),
        ),
    ]
