# Generated by Django 6.1.1 on 2026-10-03 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_identifier_schemes_of_the_instance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='errand',
            name='kind',
            field=models.CharField(max_length=40, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='kind',
            field=models.CharField(blank=True, choices=[('mobile', 'Mobile'), ('work', 'Work'), ('home', 'Home'), ('switchboard', 'Switchboard'), ('fax', 'Fax'), ('other', 'Other')], max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='label',
            field=models.CharField(blank=True, help_text='Your name for it, when none of the types above fits.', max_length=60, verbose_name='name, if Other'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='kind',
            field=models.CharField(blank=True, choices=[('home', 'Home'), ('work', 'Work'), ('postal', 'Postal'), ('other', 'Other')], max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='postaladdress',
            name='label',
            field=models.CharField(blank=True, help_text='Your name for it, when none of the types above fits.', max_length=60, verbose_name='name, if Other'),
        ),
        migrations.AlterField(
            model_name='weblink',
            name='kind',
            field=models.CharField(choices=[('social', 'Social profile'), ('repository', 'Code repository'), ('website', 'Website')], max_length=20, verbose_name='type'),
        ),
    ]
