# Generated by Django 6.1.1 on 2026-10-03 21:48

from django.db import migrations, models

from postulo.core import slugs


def rederive(apps, schema_editor):
    """A tag whose slug is empty, was cut short, or belongs to the name it had before it was
    renamed gets the slug of its present name (#356)."""
    slugs.rederive(apps.get_model("core", "Tag"), fallback="tag")


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_type_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='slug',
            field=models.SlugField(allow_unicode=True, max_length=60, verbose_name='slug'),
        ),
        migrations.RunPython(rederive, migrations.RunPython.noop),
    ]
