# Generated by Django 6.1.1 on 2026-10-05 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('core', '0029_tag_slugs'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessagingHandle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.PositiveBigIntegerField()),
                ('service', models.CharField(blank=True, max_length=40, verbose_name='service')),
                ('label', models.CharField(blank=True, help_text='What the service is called, when it is not one in the list.', max_length=60, verbose_name='name')),
                ('handle', models.CharField(max_length=255, verbose_name='handle')),
                ('is_primary', models.BooleanField(default=False, verbose_name='primary')),
                ('comparable', models.CharField(blank=True, max_length=330)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'messaging handle',
                'verbose_name_plural': 'messaging handles',
                'ordering': ('-is_primary', 'created_at', 'pk'),
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='core_messag_content_08dfe8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('content_type', 'object_id'), name='one_primary_messaging_handle_per_holder'), models.UniqueConstraint(fields=('content_type', 'object_id', 'service', 'comparable'), name='messaging_handle_unique_per_holder_and_service')],
            },
        ),
    ]
