# Generated by Django 6.1.1 on 2026-10-05 20:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_messaginghandle'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='backup_failures',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_hour',
            field=models.PositiveSmallIntegerField(choices=[(0, '00:00'), (1, '01:00'), (2, '02:00'), (3, '03:00'), (4, '04:00'), (5, '05:00'), (6, '06:00'), (7, '07:00'), (8, '08:00'), (9, '09:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00')], default=3, help_text="In the instance's time zone.", verbose_name='at'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_keep',
            field=models.PositiveSmallIntegerField(default=7, help_text='Older backups are deleted only after a new one has been written and checked. Archives you uploaded are never deleted by this.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='keep the newest'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_last_error',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_last_ok_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_last_run_at',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_last_run_ok',
            field=models.BooleanField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_schedule',
            field=models.CharField(choices=[('off', 'Off'), ('daily', 'Every day'), ('weekly', 'Every week')], default='off', max_length=10, verbose_name='scheduled backups'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='backup_weekday',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], default=0, help_text='Only for weekly backups.', verbose_name='on'),
        ),
    ]
