# Generated by Django 6.1.1 on 2026-09-04 17:29

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import postulo.documents.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoverLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(max_length=120, verbose_name='name')),
                ('subject', models.CharField(blank=True, max_length=250, verbose_name='subject')),
                ('body', models.TextField(help_text='Placeholders such as {{ company }} are filled in when sent.', verbose_name='body')),
                ('is_template', models.BooleanField(default=True, help_text='Templates appear when you send a letter with an application.', verbose_name='reusable template')),
                ('theme', models.CharField(choices=[('plain', 'Plain'), ('classic', 'Classic')], default='plain', max_length=20, verbose_name='theme')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'cover letter',
                'verbose_name_plural': 'cover letters',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('name', models.CharField(help_text='For you, not for the employer: “Backend, English”.', max_length=120, verbose_name='name')),
                ('headline', models.CharField(blank=True, max_length=200, verbose_name='headline')),
                ('summary', models.TextField(blank=True, help_text='The opening paragraph, if you use one.', verbose_name='summary')),
                ('theme', models.CharField(choices=[('plain', 'Plain'), ('classic', 'Classic')], default='plain', max_length=20, verbose_name='theme')),
                ('language', models.CharField(blank=True, help_text='Which language this variant is written in. Leave blank to follow your profile.', max_length=10, verbose_name='language')),
                ('show_contact_details', models.BooleanField(default=True, help_text='Your name, email and location, taken from your profile.', verbose_name='include contact details')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'CV',
                'verbose_name_plural': 'CVs',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='CVItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('object_id', models.PositiveIntegerField()),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('is_included', models.BooleanField(default=True, help_text='Uncheck to keep the entry on this variant but leave it off the page.', verbose_name='included')),
                ('override_highlights', models.TextField(blank=True, help_text='Replaces the master highlights on this variant only. One per line.', verbose_name='highlights for this CV')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='documents.cv', verbose_name='CV')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'CV entry',
                'verbose_name_plural': 'CV entries',
                'ordering': ('order', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='RenderedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('kind', models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Cover letter'), ('certificate', 'Certificate'), ('portfolio', 'Portfolio'), ('reference', 'Reference'), ('other', 'Other')], default='cv', max_length=20, verbose_name='kind')),
                ('file', models.FileField(upload_to=postulo.documents.models.upload_to_documents, verbose_name='file')),
                ('source_text', models.TextField(blank=True, verbose_name='text as sent')),
                ('checksum', models.CharField(blank=True, editable=False, max_length=64, verbose_name='checksum')),
                ('rendered_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='rendered on')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rendered_documents', to='applications.application', verbose_name='application')),
                ('cover_letter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renders', to='documents.coverletter', verbose_name='from cover letter')),
                ('cv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='renders', to='documents.cv', verbose_name='from CV')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'sent document',
                'verbose_name_plural': 'sent documents',
                'ordering': ('-rendered_at',),
            },
        ),
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('kind', models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Cover letter'), ('certificate', 'Certificate'), ('portfolio', 'Portfolio'), ('reference', 'Reference'), ('other', 'Other')], default='cv', max_length=20, verbose_name='kind')),
                ('file', models.FileField(upload_to=postulo.documents.models.upload_to_documents, validators=[django.core.validators.FileExtensionValidator(['pdf', 'doc', 'docx', 'odt', 'rtf', 'txt', 'png', 'jpg', 'jpeg'])], verbose_name='file')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('version', models.PositiveIntegerField(default=1, verbose_name='version')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('replaces', models.ForeignKey(blank=True, help_text='The earlier version this supersedes. The old file is kept.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='replaced_by', to='documents.uploadeddocument', verbose_name='replaces')),
            ],
            options={
                'verbose_name': 'uploaded document',
                'verbose_name_plural': 'uploaded documents',
                'ordering': ('-created_at',),
            },
        ),
        migrations.AddConstraint(
            model_name='cv',
            constraint=models.UniqueConstraint(fields=('owner', 'name'), name='unique_cv_name_per_owner'),
        ),
        migrations.AddIndex(
            model_name='cvitem',
            index=models.Index(fields=['content_type', 'object_id'], name='documents_c_content_02fb9b_idx'),
        ),
        migrations.AddConstraint(
            model_name='cvitem',
            constraint=models.UniqueConstraint(fields=('cv', 'content_type', 'object_id'), name='unique_item_per_cv'),
        ),
    ]
