# Generated by Django 6.1.1 on 2026-09-06 10:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('plugins', '0001_connection'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentCopy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('store', models.CharField(max_length=60, verbose_name='store')),
                ('label', models.CharField(blank=True, max_length=100, verbose_name='label')),
                ('status', models.CharField(choices=[('pending', 'Waiting to be sent'), ('sent', 'Archived'), ('failed', 'Failed'), ('declined', 'Not accepted')], default='pending', max_length=10, verbose_name='status')),
                ('external_id', models.CharField(blank=True, max_length=500, verbose_name='id in the store')),
                ('external_url', models.CharField(blank=True, max_length=500, verbose_name='link in the store')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='attempts')),
                ('next_attempt_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True, verbose_name='next attempt')),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='last attempt')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='sent on')),
                ('last_error', models.TextField(blank=True, verbose_name='last error')),
                ('connection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='copies', to='plugins.connection', verbose_name='connection')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('rendered', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='documents.rendereddocument', verbose_name='sent document')),
                ('upload', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='documents.uploadeddocument', verbose_name='uploaded document')),
            ],
            options={
                'verbose_name': 'document copy',
                'verbose_name_plural': 'document copies',
                'ordering': ('pk',),
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('rendered__isnull', False), ('upload__isnull', True)), models.Q(('rendered__isnull', True), ('upload__isnull', False)), _connector='OR'), name='documents_copy_of_one_document'), models.UniqueConstraint(condition=models.Q(('connection__isnull', False), ('rendered__isnull', False)), fields=('connection', 'rendered'), name='documents_copy_once_per_render'), models.UniqueConstraint(condition=models.Q(('connection__isnull', False), ('upload__isnull', False)), fields=('connection', 'upload'), name='documents_copy_once_per_upload')],
            },
        ),
    ]
