# Generated by Django 6.1.1 on 2026-09-06 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_copies'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coverletter',
            options={'ordering': ('name',), 'verbose_name': 'letter', 'verbose_name_plural': 'letters'},
        ),
        migrations.AddField(
            model_name='coverletter',
            name='kind',
            field=models.CharField(choices=[('cover', 'Cover letter'), ('motivation', 'Motivation letter'), ('speculative', 'Speculative letter'), ('follow_up', 'Follow-up note')], db_index=True, default='cover', max_length=20, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='rendereddocument',
            name='kind',
            field=models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Cover letter'), ('motivation_letter', 'Motivation letter'), ('certificate', 'Certificate'), ('portfolio', 'Portfolio'), ('reference', 'Reference'), ('other', 'Other')], default='cv', max_length=20, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='kind',
            field=models.CharField(choices=[('cv', 'CV'), ('cover_letter', 'Cover letter'), ('motivation_letter', 'Motivation letter'), ('certificate', 'Certificate'), ('portfolio', 'Portfolio'), ('reference', 'Reference'), ('other', 'Other')], default='cv', max_length=20, verbose_name='kind'),
        ),
    ]
