# Generated by Django 6.1.1 on 2026-09-06 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_letter_kinds'),
    ]

    operations = [
        migrations.AddField(
            model_name='coverletter',
            name='language',
            field=models.CharField(blank=True, help_text='Which language this letter is written in. Leave blank to follow your profile.', max_length=10, verbose_name='language'),
        ),
    ]
