# Generated by Django 6.1.1 on 2026-09-10 05:39

import postulo.documents.kinds
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0006_theme_is_a_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='kind',
            field=models.CharField(choices=[('cv', 'CV'), ('portfolio', 'Portfolio')], db_index=True, default='cv', max_length=20, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='rendereddocument',
            name='kind',
            field=models.CharField(choices=postulo.documents.kinds.choices, default='cv', max_length=20, verbose_name='kind'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='kind',
            field=models.CharField(choices=postulo.documents.kinds.choices, default='cv', max_length=20, verbose_name='kind'),
        ),
    ]
