# Generated by Django 6.1.1 on 2026-09-16 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0010_channel_employment_service'),
        ('documents', '0007_cv_kind_alter_rendereddocument_kind_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendereddocument',
            name='sent_to',
            field=models.CharField(blank=True, editable=False, max_length=250, verbose_name='sent to'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='checksum',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='checksum'),
        ),
        migrations.AlterField(
            model_name='rendereddocument',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rendered_documents', to='applications.application', verbose_name='application'),
        ),
    ]
