# Generated by Django 6.1.1 on 2026-10-03 17:24

import django.db.models.deletion
import postulo.documents.kinds
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('documents', '0013_a_language_is_a_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coverletter',
            name='kind',
            field=models.CharField(choices=[('cover', 'Cover letter'), ('motivation', 'Motivation letter'), ('speculative', 'Speculative letter'), ('follow_up', 'Follow-up note')], db_index=True, default='cover', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='cv',
            name='kind',
            field=models.CharField(choices=[('cv', 'CV'), ('portfolio', 'Portfolio')], db_index=True, default='cv', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='documentcopy',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='type of document'),
        ),
        migrations.AlterField(
            model_name='rendereddocument',
            name='kind',
            field=models.CharField(choices=postulo.documents.kinds.choices, default='cv', max_length=20, verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='rendereddocument',
            name='source_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='contenttypes.contenttype', verbose_name='type of source'),
        ),
        migrations.AlterField(
            model_name='uploadeddocument',
            name='kind',
            field=models.CharField(choices=postulo.documents.kinds.choices, default='cv', max_length=20, verbose_name='type'),
        ),
    ]
