# Generated by Django 6.1.1 on 2026-10-03 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_drop_unsent_orphan_copies'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentcopy',
            name='claimed_until',
            field=models.DateTimeField(blank=True, null=True, verbose_name='claimed until'),
        ),
    ]
