# Generated by Django 6.1.1 on 2026-10-04 06:43

import postulo.documents.themes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0016_drop_unsent_orphan_copies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='theme',
            field=models.CharField(default='plain', max_length=60, validators=[postulo.documents.themes.SetsThisKind('cv', 'portfolio')], verbose_name='theme'),
        ),
    ]
