# Generated by Django 6.1.1 on 2026-10-05 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0018_copy_claimed_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='show_birth_date',
            field=models.BooleanField(default=False, verbose_name='print your date of birth'),
        ),
        migrations.AddField(
            model_name='cv',
            name='show_birth_place',
            field=models.BooleanField(default=False, verbose_name='print your place of birth'),
        ),
    ]
