# Generated by Django 6.1.1 on 2026-10-05 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0019_cv_prints_birth_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='show_nationality',
            field=models.BooleanField(default=False, verbose_name='print your nationality'),
        ),
    ]
