# Generated by Django 6.1.1 on 2026-10-05 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0020_cv_prints_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='show_gender',
            field=models.BooleanField(default=False, verbose_name='print your gender'),
        ),
    ]
