# Generated by Django 6.1.1 on 2026-10-05 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_messaginghandle'),
        ('documents', '0021_cv_prints_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='messaging_choice',
            field=models.CharField(choices=[('default', 'Follow your details'), ('chosen', 'Chosen for this CV'), ('none', 'None')], default='default', max_length=10, verbose_name='messaging handle printed'),
        ),
        migrations.AddField(
            model_name='cv',
            name='pinned_messaging',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.messaginghandle', verbose_name='messaging handle chosen'),
        ),
    ]
