# Generated by Django 6.1.1 on 2026-10-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0022_cv_prints_messaging'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendereddocument',
            name='with_properties',
            field=models.BooleanField(default=True, editable=False, verbose_name='written with its properties'),
        ),
    ]
