# Generated by Django 6.1.1 on 2026-10-06 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_sent_document_with_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='show_eqf_level',
            field=models.BooleanField(default=False, help_text='Beside the institution, for each qualification where you have stated one. The level means little on a CV for a country outside the framework’s reach.', verbose_name='print the EQF level of my qualifications'),
        ),
    ]
