# Generated by Django 6.1.1 on 2026-10-06 08:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0023_sent_document_with_properties'),
        ('jobs', '0027_description_format'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenceLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('written_on', models.DateField(blank=True, null=True, verbose_name='written on')),
                ('valid_until', models.DateField(blank=True, null=True, verbose_name='do not send after')),
                ('delivery', models.CharField(choices=[('you', 'You send it'), ('referee', 'The referee sends it themselves')], default='you', max_length=10, verbose_name='how it reaches the employer')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('referee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reference_letters', to='jobs.contact', verbose_name='referee')),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reference_letter', to='documents.uploadeddocument', verbose_name='file')),
            ],
            options={
                'verbose_name': 'reference letter',
                'verbose_name_plural': 'reference letters',
            },
        ),
    ]
