# Generated by Django 6.1.1 on 2026-10-06 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0025_cv_prints_eqf_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddocument',
            name='damage',
            field=models.CharField(blank=True, editable=False, max_length=10, verbose_name='damage'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='size',
            field=models.PositiveBigIntegerField(blank=True, editable=False, null=True, verbose_name='size'),
        ),
        migrations.AddField(
            model_name='uploadeddocument',
            name='verified_at',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last checked'),
        ),
    ]
