# Generated by Django 6.1.1 on 2026-10-06 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0026_upload_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='show_photo',
            field=models.BooleanField(default=False, help_text='The photo from your details, beside your name. It is in the PDF and the preview; the plain text and the Word file leave it out.', verbose_name='print your CV photo'),
        ),
    ]
