# Generated by Django 6.1.1 on 2026-10-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0027_cv_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='references_on_request',
            field=models.BooleanField(default=False, help_text='A line at the end, which names nobody. A reference from your career is printed only once the person has agreed, whatever this says.', verbose_name='say that references are available on request'),
        ),
    ]
